### ISSUE TITLE
Move browserlist into package.json

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/design-system-starter#11]
**The Problem:**
We have a `.browserlistrc` file but our current project setup ignores our custom settings and our autoprefixer will only use it's default settings.

**The Fix:**
1. Delete `.browserlistrc`
1. Add the following to the `package.json`:
    ```
    "browserslist": [
      "last 1 major version",
      ">= 1%",
      "Chrome >= 68",
      "IE >= 11",
      "Safari >= 11",
      "Edge >= 16"
    ]
    ```

This can be tested by adding a custom class with `display: grid`. The compiled CSS (`dist/css/base.css`) should also include the `-ms-` prefix that is needed for IE 11.

**Comment by monika** [comment]
I can take care of this for ya!

**Comment by kaseybon** [comment]
Thank you @monika! I've assigned the card to you and I will be happy to review your pull request when it's ready!

**Comment by monika** [comment]
I've got this set up, but I wasn't able to test this by using `display: grid` because it looks like [prefix support for IE11 by Autoprefixer is off by default](https://github.com/postcss/autoprefixer#options).

I tested `::placeholder` to see prefixes for `-webkit-`, `-moz-`, and `-ms-`:

<img width="780" alt="Screen Shot 2019-10-08 at 8 19 42 PM" src="https://user-images.githubusercontent.com/316762/66449256-4aad7e00-ea09-11e9-9083-a510cfc20df2.png">

I also downgraded IE support down to IE9 and I was able to see `-ms-` prefix support for flexbox:

<img width="731" alt="Screen Shot 2019-10-08 at 7 48 51 PM" src="https://user-images.githubusercontent.com/316762/66448393-43d13c00-ea06-11e9-9a33-b0c73c9d2c88.png">

But yeah in order to test `grid` support specifically, Autoprefixer's config will need to be updated, which I thought would be outside the scope of this specific issue.
